// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxCGaEiWOSRbiHySQe1WUw0ZcyC74b2I',
    appId: '1:186870698580:web:c276d85aeffd8db90b93c1',
    messagingSenderId: '186870698580',
    projectId: 'jokee-single-serving-app',
    authDomain: 'jokee-single-serving-app.firebaseapp.com',
    storageBucket: 'jokee-single-serving-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBat-y6xQ5tirf7odjB2L5Ql98gPvUskNg',
    appId: '1:186870698580:android:f163226caebfe4270b93c1',
    messagingSenderId: '186870698580',
    projectId: 'jokee-single-serving-app',
    storageBucket: 'jokee-single-serving-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2iz2gutcWNL3i0TTjIfP8OFlbFKbu1PA',
    appId: '1:186870698580:ios:4cb6f8baa8649c730b93c1',
    messagingSenderId: '186870698580',
    projectId: 'jokee-single-serving-app',
    storageBucket: 'jokee-single-serving-app.appspot.com',
    iosClientId: '186870698580-8tksj1ebquhjagiuk0gohsglei2nulrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jokeeSingleServingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2iz2gutcWNL3i0TTjIfP8OFlbFKbu1PA',
    appId: '1:186870698580:ios:8bbe953cf36f369b0b93c1',
    messagingSenderId: '186870698580',
    projectId: 'jokee-single-serving-app',
    storageBucket: 'jokee-single-serving-app.appspot.com',
    iosClientId: '186870698580-gj1oiobecj6dd9v5cd7lvebdb4cgjv3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.jokeeSingleServingApp.RunnerTests',
  );
}
